### ISSUE TITLE
Planet not appearing

### ISSUE THREAD

**Issue by DJDarkFire** [hmcGit/UniPixelPlanet#2]
Thanks for the port of the Godot version into Unity, however when I imported the files into my own Unity 2022 LTS project, the planet does not seem to be appearing. I am not sure why this occurs, but all the other code is fine (such as the UI and the stars). Could you please help? Thank you

https://github.com/hmcGit/UniPixelPlanet/assets/139870717/cd84dbf3-351f-4caf-9b7e-0a5687961521

**Comment by hmcGit** [comment]
Hello.
I have tried with Unity 2022.3.28. It was displayed without any problem.
If you are not using URP or if you have an older URP, you can try a conversion, etc.
I have updated this project with 2022.3.38 just in case.
Thanks.

**Comment by DJDarkFire** [comment]
It works now, thank you! It appears I had to update my URP for some reason.
